"""description

Revision ID: 829c53f23756
Revises: 
Create Date: 2026-02-03 16:32:27.077346+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '829c53f23756'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.Enum('WELCOME', 'PLAN_START', 'COMPLETION', 'ENCOURAGEMENT', name='messagecontext'), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_system_message_context', 'system_messages', ['context', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('affirmations',
    sa.Column('affirmation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('ENCOURAGEMENT', 'PROGRESS', 'MINDFULNESS', 'FOCUS', name='affirmationcategory'), nullable=False),
    sa.Column('is_system_affirmation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('affirmation_id')
    )
    op.create_index('idx_affirmation_category', 'affirmations', ['category', 'is_system_affirmation'], unique=False)
    op.create_index('idx_affirmation_user', 'affirmations', ['user_id'], unique=False)
    op.create_table('daily_checkins',
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'PLANNED', 'SKIPPED', name='checkinstatus'), nullable=False),
    sa.Column('completion_icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkin_id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_checkin_user_date')
    )
    op.create_index('idx_checkin_user_date', 'daily_checkins', ['user_id', 'date'], unique=False)
    op.create_table('daily_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('voice_input_url', sa.String(length=500), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('parsed_goal', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_plan_user_date')
    )
    op.create_index('idx_plan_user_date', 'daily_plans', ['user_id', 'date'], unique=False)
    op.create_table('journal_entries',
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entry_text', sa.Text(), nullable=True),
    sa.Column('voice_recording_url', sa.String(length=500), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('is_voice_entry', sa.Boolean(), nullable=False),
    sa.Column('mood_rating', sa.Enum('GREAT', 'GOOD', 'CALM', 'STRESSED', 'OVERWHELMED', name='moodrating'), nullable=True),
    sa.Column('primary_emotion', sa.String(length=50), nullable=True),
    sa.Column('secondary_emotions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_journal_user_date')
    )
    op.create_index('idx_journal_mood', 'journal_entries', ['user_id', 'mood_rating'], unique=False)
    op.create_index('idx_journal_user_created', 'journal_entries', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_journal_user_date', 'journal_entries', ['user_id', 'date'], unique=False)
    op.create_table('onboarding_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.Enum('BREATHING_EXERCISE', 'CONSISTENCY_MESSAGE', 'PROGRESS_TRACKING', 'MOMENTUM_BUILDING', 'TRIGGER_IDENTIFICATION', 'INTENTIONAL_PLANNING', name='onboardingstepname'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('step_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voice_recording_url', sa.String(length=500), nullable=True),
    sa.Column('transcription', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id'),
    sa.UniqueConstraint('user_id', 'step_name', name='uq_onboarding_user_step')
    )
    op.create_index('idx_onboarding_user', 'onboarding_steps', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'MONTHLY', 'ANNUAL', name='subscriptiontier'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIAL', 'EXPIRED', 'CANCELLED', 'BILLING_ISSUE', name='subscriptionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revenuecat_subscriber_id', sa.String(length=255), nullable=True),
    sa.Column('revenuecat_original_app_user_id', sa.String(length=255), nullable=True),
    sa.Column('revenuecat_entitlements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_revenuecat_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', 'WEB', name='platform'), nullable=True),
    sa.Column('product_identifier', sa.String(length=100), nullable=True),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('original_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('store_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('store_original_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index('idx_subscription_status_expires', 'subscriptions', ['status', 'expires_at'], unique=False)
    op.create_index('idx_subscription_tier_status', 'subscriptions', ['tier', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_revenuecat_subscriber_id'), 'subscriptions', ['revenuecat_subscriber_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('trigger_activities',
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('SOCIAL_MEDIA', 'FOOD', 'GAMING', 'SHOPPING', 'VIDEO', 'OTHER', name='triggercategory'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('identified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.create_index('idx_trigger_user', 'trigger_activities', ['user_id'], unique=False)
    op.create_index('idx_trigger_user_active', 'trigger_activities', ['user_id', 'is_active'], unique=False)
    op.create_table('user_progress',
    sa.Column('progress_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=False),
    sa.Column('total_days_active', sa.Integer(), nullable=False),
    sa.Column('current_focus_streak', sa.Integer(), nullable=False),
    sa.Column('longest_focus_streak', sa.Integer(), nullable=False),
    sa.Column('total_journal_entries', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=True)
    op.create_table('voice_recordings',
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('transcription_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='transcriptionstatus'), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('transcription_confidence', sa.Float(), nullable=True),
    sa.Column('recording_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recording_id')
    )
    op.create_index('idx_recording_reference', 'voice_recordings', ['recording_type', 'reference_id'], unique=False)
    op.create_index('idx_recording_status', 'voice_recordings', ['transcription_status'], unique=False)
    op.create_index('idx_recording_user', 'voice_recordings', ['user_id'], unique=False)
    op.create_table('daily_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('VOICE_INTENSITY', 'ENERGY_LEVEL', 'STRESS_LEVEL', name='metrictype'), nullable=False),
    sa.Column('metric_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.entry_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_table('journal_insights',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.Enum('ENERGETIC_MORNING', 'MIDDAY_STRESS', 'EVENING_CALM', 'PATTERN_DETECTED', 'EMOTIONAL_AWARENESS', 'POSITIVE_BEHAVIOR', name='insighttype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.entry_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_table('subscription_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('PURCHASE', 'RENEWAL', 'CANCELLATION', 'EXPIRATION', 'REACTIVATION', 'UPGRADE', 'DOWNGRADE', 'REFUND', 'BILLING_ISSUE', name='subscriptioneventtype'), nullable=False),
    sa.Column('previous_tier', sa.Enum('FREE', 'MONTHLY', 'ANNUAL', name='subscriptiontier'), nullable=True),
    sa.Column('new_tier', sa.Enum('FREE', 'MONTHLY', 'ANNUAL', name='subscriptiontier'), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('store_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('revenuecat_event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('idx_sub_history_event_date', 'subscription_history', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_sub_history_subscription', 'subscription_history', ['subscription_id', 'created_at'], unique=False)
    op.create_index('idx_sub_history_user_event', 'subscription_history', ['user_id', 'event_type', 'created_at'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('NON_NEGOTIABLE', 'IMPORTANT', 'OPTIONAL', name='taskcategory'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_plans.plan_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('idx_task_plan_order', 'tasks', ['plan_id', 'order_index'], unique=False)
    op.create_index('idx_task_user_completed', 'tasks', ['user_id', 'completed', 'due_date'], unique=False)
    op.create_index('idx_task_user_date', 'tasks', ['user_id', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_user_date', table_name='tasks')
    op.drop_index('idx_task_user_completed', table_name='tasks')
    op.drop_index('idx_task_plan_order', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_sub_history_user_event', table_name='subscription_history')
    op.drop_index('idx_sub_history_subscription', table_name='subscription_history')
    op.drop_index('idx_sub_history_event_date', table_name='subscription_history')
    op.drop_table('subscription_history')
    op.drop_table('journal_insights')
    op.drop_table('daily_metrics')
    op.drop_index('idx_recording_user', table_name='voice_recordings')
    op.drop_index('idx_recording_status', table_name='voice_recordings')
    op.drop_index('idx_recording_reference', table_name='voice_recordings')
    op.drop_table('voice_recordings')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('idx_trigger_user_active', table_name='trigger_activities')
    op.drop_index('idx_trigger_user', table_name='trigger_activities')
    op.drop_table('trigger_activities')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_revenuecat_subscriber_id'), table_name='subscriptions')
    op.drop_index('idx_subscription_tier_status', table_name='subscriptions')
    op.drop_index('idx_subscription_status_expires', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_onboarding_user', table_name='onboarding_steps')
    op.drop_table('onboarding_steps')
    op.drop_index('idx_journal_user_date', table_name='journal_entries')
    op.drop_index('idx_journal_user_created', table_name='journal_entries')
    op.drop_index('idx_journal_mood', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('idx_plan_user_date', table_name='daily_plans')
    op.drop_table('daily_plans')
    op.drop_index('idx_checkin_user_date', table_name='daily_checkins')
    op.drop_table('daily_checkins')
    op.drop_index('idx_affirmation_user', table_name='affirmations')
    op.drop_index('idx_affirmation_category', table_name='affirmations')
    op.drop_table('affirmations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_system_message_context', table_name='system_messages')
    op.drop_table('system_messages')
    # ### end Alembic commands ###
